version: 0.0
os: linux
files:
  - source: /
    destination: /home/admin/bifrost-io
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/admin
    pattern: "**"
    owner: admin
    group: admin
    mode: 755
hooks:
  ApplicationStop:
    - location: scripts/StopServer.sh
      timeout: 300
      runas: admin
  AfterInstall:
    - location: scripts/InstallDependencies.sh
      timeout: 300
      runas: admin
  ApplicationStart:
    - location: scripts/StartServer.sh
      timeout: 300
      runas: admin